### ISSUE TITLE
[🕹️]BUG Editing Link screen scrollbar

### ISSUE THREAD

**Issue by ykburda** [mfts/papermark#702] opened 2024-10-09 08:47 UTC
### What side quest or challenge are you solving?

Bug

### Points

?

### Description

Link editing page doesn't fit to screen. There should be scrollbar. 
![image](https://github.com/user-attachments/assets/3e21c54a-d4ba-420a-94b2-a558778006d9)

### Provide proof that you've completed the task

?

**Comment by swarupn17** [comment] 2024-10-09 09:10
Hello @ykburda I can do this task please can you assign it to me.
Thanks !

**Comment by AshishViradiya153** [comment] 2024-10-09 09:21
Where exactly is it happening? @ykburda

**Comment by ykburda** [comment] 2024-10-09 09:24
![image](https://github.com/user-attachments/assets/ab56a818-57e9-42e2-8507-c78b5f9b207d)

**Comment by AshishViradiya153** [comment] 2024-10-09 10:54
I tried everything to replicate this, but based on the code, we always have a scroll no matter how much it expands. The strange thing in the first image is the space on the right side, which we don’t have in the edit link sidebar.

**Comment by AshishViradiya153** [comment] 2024-10-09 11:40
@ykburda Could you please add a short video if possible, so I can take a closer look? 
I will add more space at the bottom so that the last one appears in the middle instead of to much at the bottom.

**Comment by ykburda** [comment] 2024-10-09 13:25
It's not screen fit problem. When i click to edit link button. It's opening a popup right side of window. It has many fields and i can not scroll because it doesn't show scrollbar.It's somehow possible with pagedown or down keyboard button.

**Comment by DeepaPrasanna** [comment] 2024-10-09 14:15
hey @AshishViradiya153  you should first assign yourself and then link a PR

**Comment by AshishViradiya153** [comment] 2024-10-09 14:51
@ykburda It's not a bug. There are two dropdown fields that should close after opening if the user starts scrolling or interacting with something else.

**Comment by AshishViradiya153** [comment] 2024-10-09 15:24
@DeepaPrasanna Yes, You are right. thing is i did not create pr before someone assign there self, i serve the customer, issue creater is not a developer, i just try to ask him some question so we can find exat root cause of bug, pr contains just some user experience improvement. this issue is not a bug.

**Comment by AshishViradiya153** [comment] 2024-10-09 17:55
Okay i will recheck ui.

**Closed** 2024-10-16 04:28 UTC
Labels: 🕹️ oss.gg, hacktoberfest
